name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch or test branch
  push:
    branches: [ main, feature/deploy-setting-test ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make artifact uploads
    permissions:
      contents: read
      pages: write
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Build with Astro
        run: bun run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Specify a GitHub deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
